---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/doctors/create":
    post:
      summary: Create a doctor
      tags:
      - api/doctors
      parameters: []
      responses:
        '201':
          description: doctor created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                city:
                  type: string
                image:
                  type: string
                description:
                  type: string
                speciality:
                  type: string
              required:
              - name
              - city
              - image
              - description
              - speciality
          application/xml:
            schema:
              type: object
              properties:
                name:
                  type: string
                city:
                  type: string
                image:
                  type: string
                description:
                  type: string
                speciality:
                  type: string
              required:
              - name
              - city
              - image
              - description
              - speciality
  "/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
  "/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    patch:
      summary: update doctor
      responses:
        '200':
          description: successful
    put:
      summary: update doctor
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
